name: Chat
version: ${version}
description: An elegant, multifunctional chat plugin
authors: [TheBlockBender, SlagHoedje]
softdepend: [PlaceholderAPI]

main: me.theblockbender.hive.Chat

commands:
  tell:
    description: Send a private message to someone
    aliases: [pm, message, msg, t, whisper]
  reply:
    description: Reply to a private message you have received
    aliases: [r]
  chat:
    description: Main chat command

permissions:
  chat.admin.*:
    description: Gives access to all admin permissions.
    default: op
    children:
      chat.admin.version: true
      chat.admin.help: true
      chat.admin.reload: true
      chat.color: true
  chat.admin.version:
    description: Allows the user to view the version of chat.
    default: op
  chat.admin.help:
    description: Allows the user to view the help page of /chat
    default: op
  chat.admin.reload:
    description: Allows the user to reload the plugin
    default: op
  chat.color:
    description: Allows the user to chat with color codes
    default: op

  chat.user.*:
    description: Gives access to all user permissions.
    default: true
    children:
      chat.user.chat: true
      chat.user.msg: true
  chat.user.chat:
    description: Allow the user to send chat messages.
    default: true
  chat.user.msg:
    description: Allow the user to send private messages and reply to them
    default: true