name: AceChat
version: 1.0.0
description: An elegant, multifunctional chat plugin
author: SlagHoedje
softdepend: [PlaceholderAPI]

main: com.slaghoedje.acechat.AceChat

commands:
  tell:
    description: Send a private message to someone
    aliases: [pm, message, msg, t]
  chat:
    description: Main AceChat command
    aliases: [acechat, ac]

permissions:
  acechat.admin.*:
    description: Gives access to all admin permissions.
    default: op
    children:
      acechat.admin.clearchat: true
      acechat.admin.version: true
      acechat.admin.help: true
      acechat.admin.reload: true
      acechat.admin.clearchat.bypass: true
      acechat.admin.mutechat: true
      acechat.admin.mutechat.bypass: true
  acechat.admin.clearchat:
    description: Allows the user to clear the chat
    default: op
  acechat.admin.version:
    description: Allows the user to view the version of AceChat
    default: op
  acechat.admin.help:
    description: Allows the user to view the help page of /chat
    default: op
  acechat.admin.reload:
    description: Allows the user to reload the plugin
    default: op
  acechat.admin.clearchat.bypass:
    description: Let's the user not see the chat clear
    default: op
  acechat.admin.mutechat:
    description: Allows the user to mute the global chat
    default: op
  acechat.admin.mutechat.bypass:
    description: Allows the user to chat while the global chat is muted
    default: op

  acechat.user.*:
    description: Gives access to all default user permissions.
    default: true
    children:
      acechat.user.chat: true
  acechat.user.chat:
    description: Allow the user to send chat messages.
    default: true